

<BR>
<div align="center">
 <Font color = "#3CA0BD"><Label><strong>PROCURADURÍA GENERAL DE LA REPÚBLICA</strong></Label></Font>
</div>
<div align="center">
  <Font color ="#3CA0BD"><Label><strong>COORDINACIÓN DE PLANEACI&Oacute;N, DESARROLLO E INNOVACIÓN INSTITUCIONAL</strong></Label></Font>
</div>
<div align="center">
  <Font color = "#3CA0BD"><Label><strong>DIRECCIÓN GENERAL DE FORMACIÓN PROFESIONAL</strong></Label></Font>
</div>
<BR>
